apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: yq06imecz-go 
  janus-idp.io/tekton: yq06imecz-go
  backstage.io/kubernetes-id: yq06imecz-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: yq06imecz-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml