apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: yq06imecz-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: yq06imecz-go 
  name: yq06imecz-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: yq06imecz-go 
